[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[dev]
  functions = "netlify/functions"
  publish = "."


# Map /api/* to Netlify Functions (e.g., /api/checkout -> /.netlify/functions/checkout)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
